# Generated by Django 3.0.5 on 2020-04-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mob_no', models.IntegerField()),
                ('to_mob_no', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
